# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-15 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_mensaje_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='fichero',
            field=models.FileField(blank=True, null=True, upload_to='static/documents'),
        ),
    ]
