# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-14 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20171214_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='/static/img/default/defaultProfile.png', upload_to='photos/'),
        ),
    ]
